package com.health.app.domain;

public enum EventToNotify {
	USER_PROFILE_ADD,
	USER_PROFILE_UPDATE,
	CONFIRMATION_OF_APPOINTMET_BOOKING,
	CANCELATION_APPOINTMENT_BOOKING,
	UPCOMING_EVENT,
	PASSWORD_EXPIRY,
	BLOOD_DONATION
}
