package com.test.app.domain.enumeration;

public enum ReturnCodes {
	USER_EXISTs,
	SUCCESS,
	DATABASE_OPERATION_FAILED,
	USER_DOESNOT_EXISTS,
	USER_ADD_FAILED,
	FAILED,
	HAS_PERMISSION,
	DOESNOT_HAVE_PERMISSION,
	ALL_READY_HAS_PERMISSION,
	LAB_DOESNOT_EXIT,
	HOSPITAL_DOESNOT_EXIT,
	USER_ACCOUNT_ACTIVATED,
	USER_ACCOUNT_DEACTIVATED,
	PASSWORD_UPDATE_SUCCESS,
	PASSWORD_UPDATE_FAILED,
	DOCTOR_ADD_SUCCESS,
	DOCTOR_ADD_FAILED,
	OTP_SEND_FAILED,
	OTP_SEND_SUCCESS,
	USER_ACCOUNT_IS_ALREADY_ACTIVATED,
}

